---
title: "MATH/COSC 3570 - Introduction to Data Science"
tbl-colwidths: [5,10,30,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
| Week | Date        | Topic                                             |                To Do                |                                             Slides                                              |                                                                    Lab Exercise                                                                    |            Homework             |                      Lab Presentation                      | Project                                                      |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|--------|
|  1   | Tue, Jan 16 | Greetings + Overview of Data Science              |  [📖](/weeks/week-1.html "Week 1")  | [🖥️](/slides/01-syllabus.html "01-Syllabus") [🖥️](/slides/02-datascience.html "02-datascience") |                                                                                                                                                    |                                 |                                                            |                                                              |
|      | Thu, Jan 18 | Posit Cloud and Git/GitHub Introduction           |                                     |                             [🖥️](/slides/03-posit.html "03-posit")                              |                          [📋](/exercise/lab00-posit.html "lab00-posit")[📋](/exercise/lab01-rscript.html "lab01-rscript")                          |                                 |                                                            |                                                              |
|  2   | Tue, Jan 23 | Connecting Posit Cloud with GitHub                |  [📖](/weeks/week-2.html "Week 2")  |                               [🖥️](/slides/04-git.html "04-git")                                |                                                     [📋](/exercise/lab00-git.html "lab00-git")                                                     |                                 |                                                            |                                                              |
|      | Thu, Jan 25 | Quarto                                            |                                     |                            [🖥️](/slides/05-quarto.html "05-quarto")                             | [📋](/exercise/lab02-quarto.html "lab02-quarto")[📋](/exercise/lab03-markdown.html "lab03-markdown")[📋](/exercise/lab04-chunk.html "lab04-chunk") |                                 |                                                            |                                                              |
|  3   | Tue, Jan 30 | Quarto                                            |                                     |                                                                                                 |                                                                                                                                                    |                                 |                                                            |                                                              |
|      | Thu, Feb 1  | R/Python Programming                              |  [📖](/weeks/week-3.html "Week 3")  |                            [🖥️](/slides/06-syntax.html "06-syntax")                             |                                                                                                                                                    |                                 |                                                            |                                                              |
|  4   | Tue, Feb 6  | Python Programming                                |                                     |                                                                                                 |                               [📋](/exercise/lab05-rtype.html "lab05-rtype")[📋](/exercise/lab06-py.html "lab06-py")                               |                                 |                                                            |                                                              |
|      | Thu, Feb 8  | R Tidyverse                                       |  [📖](/weeks/week-4.html "Week 4")  |                           [🖥️](/slides/07-package.html "07-package")                            |                                                                                                                                                    |    [✍️](/hw/hw1.html "hw1")     |                                                            |                                                              |
|  5   | Tue, Feb 13 | Python Pandas/NumPy                               |                                     |                                                                                                 |                           [📋](/exercise/lab08-tibble.html "lab08-tibble")[📋](/exercise/lab09-numpy.html "lab09-numpy")                           |                                 |        [✅](/exercise/lab07-plot.html "lab07-plot")        |                                                              |
|      | Thu, Feb 15 | Data Importing                                    |  [📖](/weeks/week-5.html "Week 5")  |                            [🖥️](/slides/08-import.html "08-import")                             |                                                  [📋](/exercise/lab10-import.html "lab10-import")                                                  |                                 |                                                            |                                                              |
|  6   | Tue, Feb 20 | Data Importing                                    |                                     |                                                                                                 |                                                                                                                                                    |                                 |                                                            |                                                              |
|      | Thu, Feb 22 | Data Visualization-ggplot2                        |  [📖](/weeks/week-6.html "Week 6")  |                           [🖥️](/slides/09-ggplot2.html "09-ggplot2")                            |                                                 [📋](/exercise/lab11-ggplot2.html "lab11-ggplot2")                                                 |                                 |                                                            |                                                              |
|  7   | Tue, Feb 27 | Data Visualization-categorical and numerical data |  [📖](/weeks/week-7.html "Week 7")  |                               [🖥️](/slides/10-viz.html "10-viz")                                |                    [📋](/exercise/lab12-facet.html "lab12-facet")[📋](/exercise/lab13-visualization.html "lab13-visualization")                    |                                 |                                                            |                                                              |
|      | Thu, Feb 29 | Interactive Data Visualization                    |                                     |                   [🖥️](/slides/11-interactive-viz.html "11-interactive-viz")                    |                                                                                                                                                    |                                 |                                                            |                                                              |
|  8   | Tue, Mar 5  | Data Wrangling - one data frame                   |  [📖](/weeks/week-8.html "Week 8")  |                           [🖥️](/slides/12-dplyr-1.html "12-dplyr-1")                            |                                                   [📋](/exercise/lab15-dplyr.html "lab15-dplyr")                                                   |                                 | [✅](/exercise/lab14-interactive.html "lab14-interactive") |                                                              |
|      | Thu, Mar 7  | Data Wrangling - two data frames                  |                                     |                           [🖥️](/slides/13-dplyr-2.html "13-dplyr-2")                            |                                                    [📋](/exercise/lab16-join.html "lab16-join")                                                    |                                 |                                                            |                                                              |
|  9   | Tue, Mar 12 | ***NO CLASS: Spring break***                      |                                     |                                                                                                 |                                                                                                                                                    |                                 |                                                            |                                                              |
|      | Thu, Mar 14 | ***NO CLASS: Spring break***                      |                                     |                                                                                                 |                                                                                                                                                    |                                 |                                                            |                                                              |
|  10  | Tue, Mar 19 | Data Wrangling - tidyr                            | [📖](/weeks/week-10.html "Week 10") |                             [🖥️](/slides/14-tidyr.html "14-tidyr")                              |                                                   [📋](/exercise/lab17-tidyr.html "lab17-tidyr")                                                   | [✍️](/hw/hw2.html "Homework 2") |                                                            |                                                              |
|      | Thu, Mar 21 | Probabilistic and Statistical Simulation          |                                     |                          [🖥️](/slides/15-probstat.html "15-probstat")                           |                                                    [📋](/exercise/lab18-prob.html "lab18-prob")                                                    |                                 |                                                            |                                                              |
|  11  | Tue, Mar 26 | Probabilistic and Statistical Simulation          |                                     |                                                                                                 |                                                      [📋](/exercise/lab19-ci.html "lab19-ci")                                                      |                                 |                                                            |                                                              |
|      | Thu, Mar 28 | ***NO CLASS: Easter break***                      |                                     |                                                                                                 |                                                                                                                                                    |                                 |                                                            | Team Up [📂](project-description.html "project-description") |
|  12  | Tue, Apr 2  | Linear Regression                                 | [📖](/weeks/week-12.html "Week 12") |                        [🖥️](/slides/16-linear-reg.html "16-linear-reg")                         |                                                                                                                                                    |                                 |                                                            |                                                              |
|      | Thu, Apr 4  | Linear Regression                                 |                                     |                                                                                                 |                                                     [📋](/exercise/lab20-slr.html "lab20-slr")                                                     |                                 |                                                            |                                                              |
|  13  | Tue, Apr 9  | Logistic Regression                               | [📖](/weeks/week-13.html "Week 13") |                      [🖥️](/slides/17-logistic-reg.html "17-logistic-reg")                       |                                                                                                                                                    |                                 |                                                            |                                                              |
|      | Thu, Apr 11 | Logistic Regression                               |                                     |                                                                                                 |                                                [📋](/exercise/lab21-logistic.html "lab21-logistic")                                                |    [✍️](/hw/hw3.html "hw3")     |                                                            |                                                              |
|  14  | Tue, Apr 16 | K-Nearest Neighbors                               | [📖](/weeks/week-14.html "Week 14") |                               [🖥️](/slides/18-knn.html "18-knn")                                |                                                                                                                                                    |                                 |                                                            |                                                              |
|      | Thu, Apr 18 | K-Nearest Neighbors                               |                                     |                                                                                                 |                                                     [📋](/exercise/lab22-knn.html "lab22-knn")                                                     |                                 |                                                            |                                                              |
|  15  | Tue, Apr 23 | Principal Component Analysis                      | [📖](/weeks/week-15.html "Week 15") |                               [🖥️](/slides/19-pca.html "19-pca")                                |                                                                                                                                                    |                                 |                                                            |                                                              |
|      | Thu, Apr 25 | Principal Component Analysis                      |                                     |                                                                                                 |                                                     [📋](/exercise/lab23-pca.html "lab23-pca")                                                     |                                 |                                                            | Proposal [📂](project-work.html "project-work")              |
|  16  | Tue, Apr 30 | K-Means Clustering                                | [📖](/weeks/week-16.html "Week 16") |                            [🖥️](/slides/20-kmeans.html "20-kmeans")                             |                                                                                                                                                    |                                 |                                                            |                                                              |
|      | Thu, May 2  | Summary                                           |                                     |                              [🖥️](/slides/summary.html "Summary")                               |                                                  [📋](/exercise/lab24-kmeans.html "lab24-kmeans")                                                  |                                 |                                                            |                                                              |
:::

I reserve the right to make changes to the schedule.

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Present | Project |
|-------|-------|-------|:-----:|:-----:|:-----:|:-------------:|:-----:|:-----:|:-----:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |   ✅    |   📂    |
